version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: "Second step"
          command: 
            ls -al
            echo '^^^The files in your repo^^^'
      
